# Generated by Django 3.1.4 on 2020-12-28 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0002_auto_20201228_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='comments',
            field=models.ManyToManyField(related_name='comments_owned', through='ads.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
